services:
  printscript-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: printscript-ui
    ports:
      - "5173:80"
    environment:
      - VITE_NGINX_URL=http://reverseproxy:80
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
