
services:
  printscript-ui:
    build: .
    container_name: printscript-ui
    ports:
      - "8084:80"
    environment:
        REACT_APP_API_URL: http://nginx:80
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: printscript-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/html:ro
    networks:
        - shared_network
    depends_on:
      - printscript-ui


networks:
  shared_network:
    driver: bridge
    external: true
